const videos = [
    {
      id: 1,
      title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam alias facilis velit tenetur animi ipsum corrupt",
      channel: "Nikhil",
      views: "100k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "gaming",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 2,
      title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam alias facilis velit tenetur animi ipsum corrupt",
      channel: "Rajeev",
      views: "200k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "gaming",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 3,
      title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam alias facilis velit tenetur animi ipsum corrupt",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "gaming",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 4,
      title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam alias facilis velit tenetur animi ipsum corrupti rem odit sit officiis.",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "gaming",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 5,
      title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam alias facilis velit tenetur",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "gaming",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 6,
      title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam alias facilis velit tenetur animi ipsum",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "music",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 7,
      title: "Video Number 7",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "music",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 8,
      title: "Video Number 8",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 9,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 10,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "entertainment",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 11,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "entertainment",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 12,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "news",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 13,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 14,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 15,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k"
    },
    {
      id: 16,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "cricket",
      likes:240,
      dislikes:10,
      subscribers:"250k" 
    },
    {
      id: 17,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "cricket",
      likes:240,
      dislikes:10,
      subscribers:"250k" 
    },
    {
      id: 18,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "cricket",
      likes:240,
      dislikes:10,
      subscribers:"250k" 
    },
    {
      id: 19,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k" 
    },
    {
      id: 20,
      title: "Video Number 9",
      channel: "Athishay",
      views: "500k",
      timestamp: "1 hour ago",
      image: require('../images/thumb.avif'),
      catergory: "live",
      likes:240,
      dislikes:10,
      subscribers:"250k" 
    }
  ]
  export default videos